import React from "react";
import "./Termsandconditions.css";
import { Link } from "react-router-dom";

const Termsandconditions = () => {
  return (
    <div className="container">
      <div className="termsandconitionsContainer inter">
        <div className="termsandconitionsContainerFirst">
          <p
            style={{
              fontSize: "24px",
              fontWeight: "500",
              margin: "0",
              marginBottom: "16px",
              width: "1137px",
            }}
          >
            Terms & Conditions
          </p>
          <p style={{ fontSize: "18px", fontWeight: "400", margin: "0" }}>
            Please read the Terms and Conditions carefully before using
            Babaldeals.com.
          </p>
          <p style={{ fontSize: "18px", fontWeight: "400", margin: "0" }}>
            This electronic record is generated by a computer system and does
            not require any physical or digital signatures.
          </p>
        </div>
        <ol>
          <li className="TCList">
            INTRODUCTION
            <p
              style={{
                fontSize: "18px",
                fontWeight: "400",
                marginBottom: "45px",
                lineHeight: "28px",
                width: "1137px",
              }}
            >
              Welcome to Ecommerce.com. We are an online marketplace and these
              are the terms and conditions governing your access and use of
              Ecommerce along with its related sub-domains, sites, mobile app,
              services and tools (the "Site"). By using the Site, you hereby
              accept these terms and conditions (including the linked
              information herein) and represent that you agree to comply with
              these terms and conditions (the "User Agreement"). This User
              Agreement is deemed effective upon your use of the Site which
              signifies your acceptance of these terms. If you do not agree to
              be bound by this User Agreement please do not access, register
              with or use this Site. This site is owned and operated by Krezona
              (Registration No.125263/71/72).
            </p>
            <p
              style={{
                fontSize: "18px",
                fontWeight: "400",
                // marginBottom: "60px",
                lineHeight: "28px",
                width: "1137px",
              }}
            >
              The Site reserves the right to change, modify, add, or remove
              portions of these Terms and Conditions at any time without any
              prior notification. Changes will be effective when posted on the
              Site with no other notice provided. Please check these Terms and
              Conditions regularly for updates. Your continued use of the Site
              following the posting of changes to Terms and Conditions of use
              constitutes your acceptance of those changes.
            </p>
          </li>
          <li className="TCList">CONDITION OF US</li>
          <ol style={{ listStyleType: "upper-alpha" }}>
            <li className="TCList">
              YOUR ACCOUNT
              <p
                style={{
                  fontSize: "18px",
                  fontWeight: "400",
                  marginBottom: "45px",
                  lineHeight: "28px",
                  width: "1137px",
                }}
              >
                To access certain services offered by the platform, we may
                require that you create an account with us or provide personal
                information to complete the creation of an account. We may at
                any time in our sole and absolute discretion, invalidate the
                username and/or password without giving any reason or prior
                notice and shall not be liable or responsible for any losses
                suffered by, caused by, arising out of, in connection with or by
                reason of such request or invalidation.
              </p>
              <p
                style={{
                  fontSize: "18px",
                  fontWeight: "400",
                  marginBottom: "45px",
                  lineHeight: "28px",
                  width: "1137px",
                }}
              >
                You are responsible for maintaining the confidentiality of your
                user identification, password, account details and related
                private information. You agree to accept this responsibility and
                ensure your account and its related details are maintained
                securely at all times and all necessary steps are taken to
                prevent misuse of your account. You should inform us immediately
                if you have any reason to believe that your password has become
                known to anyone else, or if the password is being, or is likely
                to be, used in an unauthorized manner. You agree and acknowledge
                that any use of the Site and related services offered and/or any
                access to private information, data or communications using your
                account and password shall be deemed to be either performed by
                you or authorized by you as the case may be. You agree to be
                bound by any access of the Site and/or use of any services
                offered by the Site (whether such access or use are authorized
                by you or not). You agree that we shall be entitled (but not
                obliged) to act upon, rely on or hold you solely responsible and
                liable in respect thereof as if the same were carried out or
                transmitted by you. You further agree and acknowledge that you
                shall be bound by and agree to fully indemnify us against any
                and all losses arising from the use of or access to the Site
                through your account.
              </p>
              <p
                style={{
                  fontSize: "18px",
                  fontWeight: "400",
                  // marginBottom: "60px",
                  lineHeight: "28px",
                  width: "1137px",
                }}
              >
                Please ensure that the details you provide us with are correct
                and complete at all times. You are obligated to update details
                about your account in real time by accessing your account
                online. For pieces of information you are not able to update by
                accessing Your Account on the Site, you must inform us via our
                customer service communication channels to assist you with these
                changes. We reserve the right to refuse access to the Site,
                terminate accounts, remove or edit content at any time without
                prior notice to you. We may at any time in our sole and absolute
                discretion, request that you update your Personal Data or
                forthwith invalidate the account or related details without
                giving any reason or prior notice and shall not be liable or
                responsible for any losses suffered by or caused by you or
                arising out of or in connection with or by reason of such
                request or invalidation. You hereby agree to change your
                password from time to time and to keep your account secure and
                also shall be responsible for the confidentiality of your
                account and liable for any disclosure or use (whether such use
                is authorised or not) of the username and/or password.
              </p>
            </li>
            <li className="TCList">
              PRIVACY
              <p
                style={{
                  fontSize: "18px",
                  fontWeight: "400",
                  // marginBottom: "45px",
                  lineHeight: "28px",
                  width: "1140px",
                }}
              >
                Please review our{" "}
                <Link
                  to="/privacypolicy"
                  style={{ color: "inherit", textDecoration: "none" }}
                >
                  <span style={{ color: "#FA902D" }}>Privacy Agreement</span>
                </Link>
                , which also governs your visit to the Site. The personal
                information / data provided to us by you or your use of the Site
                will be treated as strictly confidential, in accordance with the
                Privacy Agreement and applicable laws and regulations. If you
                object to your information being transferred or used in the
                manner specified in the Privacy Agreement, please do not use the
                Site.
              </p>
            </li>
            <li className="TCList">
              LICENCE TO ACCESS TO THE SITE
              <p
                style={{
                  fontSize: "18px",
                  fontWeight: "400",
                  marginBottom: "45px",
                  lineHeight: "28px",
                  width: "1140px",
                }}
              >
                We require that by accessing the Site, you confirm that you can
                form legally binding contracts and therefore you confirm that
                you are at least 18 years of age or are accessing the Site under
                the supervision of a parent or legal guardian. We grant you a
                non-transferable, revocable and non-exclusive license to use the
                Site, in accordance with the Terms and Conditions described
                herein, for the purposes of shopping for personal items and
                services as listed to be sold on the Site. Commercial use or use
                on behalf of any third party is prohibited, except as explicitly
                permitted by us in advance. If you are registering as a business
                entity, you represent that you have the authority to bind that
                entity to this User Agreement and that you and the business
                entity will comply with all applicable laws relating to online
                trading. No person or business entity may register as a member
                of the Site more than once. Any breach of these Terms and
                Conditions shall result in the immediate revocation of the
                license granted in this paragraph without notice to you.
              </p>
              <p
                style={{
                  fontSize: "18px",
                  fontWeight: "400",
                  // marginBottom: "60px",
                  lineHeight: "28px",
                  width: "1140px",
                }}
              >
                You agree and undertake not to perform restricted activities
                listed within this section; undertaking these activities will
                result in an immediate cancellation of your account, services,
                reviews, orders or any existing incomplete transaction with us
                and in severe cases may also result in legal action.
              </p>
            </li>
          </ol>
        </ol>
      </div>
    </div>
  );
};

export default Termsandconditions;
